<Project Sdk="Microsoft.NET.Sdk">
<PropertyGroup><TargetFramework>net472</TargetFramework><OutputType>Exe</OutputType><AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects><GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType><IsPackable>false</IsPackable></PropertyGroup>
<ItemGroup>
<PackageReference Include="Microsoft.AspNet.WebApi.OwinSelfHost" Version="5.3.0"/>
<PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net472" Version="1.0.3" PrivateAssets="all"/>
<ProjectReference Include="../../src/Company.ErrorManagement.WebApi2/Company.ErrorManagement.WebApi2.csproj"/>
<Reference Include="System.Data"/>
</ItemGroup></Project>
